//foi gerado automaticamente!!!
//
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNmgPPpktm-m1J_K0-AzxmBuNj8seck0Q',
    appId: '1:190453105339:web:b1cc0c12923a767464df9e',
    messagingSenderId: '190453105339',
    projectId: 'larfeito',
    authDomain: 'larfeito.firebaseapp.com',
    storageBucket: 'larfeito.firebasestorage.app',
    measurementId: 'G-40L9LKD99F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkY6Nv5dm6BQVnyTsN29iIZd-pB2y2Wuw',
    appId: '1:190453105339:android:679777562361010064df9e',
    messagingSenderId: '190453105339',
    projectId: 'larfeito',
    storageBucket: 'larfeito.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJKlboBft8rBMnDmsnU3WxDKFUdR-NT8w',
    appId: '1:190453105339:ios:3c45d4336585ed3f64df9e',
    messagingSenderId: '190453105339',
    projectId: 'larfeito',
    storageBucket: 'larfeito.firebasestorage.app',
    iosClientId: '190453105339-vs1c27tnu3ovau77uo6v9rgobi7466vj.apps.googleusercontent.com',
    iosBundleId: 'com.example.larFeito',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJKlboBft8rBMnDmsnU3WxDKFUdR-NT8w',
    appId: '1:190453105339:ios:3c45d4336585ed3f64df9e',
    messagingSenderId: '190453105339',
    projectId: 'larfeito',
    storageBucket: 'larfeito.firebasestorage.app',
    iosClientId: '190453105339-vs1c27tnu3ovau77uo6v9rgobi7466vj.apps.googleusercontent.com',
    iosBundleId: 'com.example.larFeito',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNmgPPpktm-m1J_K0-AzxmBuNj8seck0Q',
    appId: '1:190453105339:web:832e69686dd1eda064df9e',
    messagingSenderId: '190453105339',
    projectId: 'larfeito',
    authDomain: 'larfeito.firebaseapp.com',
    storageBucket: 'larfeito.firebasestorage.app',
    measurementId: 'G-BEQYVXRNSD',
  );
}
